config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'boards#index'

  resources :boards do
    resources :lists
  end

  scope 'lists/:list_id', as: 'list' do
    resources :tasks
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :lists, dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :update, :edit, :destroy]
  def index
    @boards = current_user.boards
  end

  def show

  end

  def new
    @board = Board.new
    render partial: 'form'
  end

  def create
    @board = current_user.boards.new(board_params)

    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def edit
    render partial: 'form'
  end

  def update
    if @board.update(board_params)
      redirect_to boards_path
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private

    def set_board
      @board = current_user.boards.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:name)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  


  def index
    @lists = @board.lists.all
  end

  def show
    
  end

  def new
    @list = @board.lists.new
    render partial: "form"
  end

  def create
    @list = @board.lists.new(list_params)

    if @list.save
      redirect_to board_lists_path(@board, @list)
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @list.update(list_params)
      redirect_to board_lists_path(@board, @list)
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to board_lists_path
  end




  private

    def set_board
      @board = Board.find(params[:board_id])
    end

    def set_list
      @list = List.find(params[:id])
    end



    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  def index
  end

  def show
  end

  def new
    @task = Task.new
    render partial: 'form'
  end

  def create
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to board_list_path(@list.board_id, @list)
    else
      render :new
    end
  end

  def edit
    render partial: 'form'
  end

  def update
    if @task.update(task_params)
      redirect_to board_list_path(@list.board_id, @list)
    else
      render :edit
    end
  end


  def destroy

    @task.destroy
    redirect_to board_list_path(@list.board_id, @list)
  end

  private
    def set_list
      @list = List.find(params[:list_id])
    end
    
    def set_task
      @task = Task.find(params[:id])
    end
    
    def task_params
      params.require(:task).permit(:name, :body)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<h1><%= @board.id ? 'Edit Board' : 'Create Board' %></h1>
<hr />
<%= form_for @board do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/boards/edit.html.erb
<h1>Boards#edit</h1>
<p>Find me in app/views/boards/edit.html.erb</p>

app/views/boards/index.html.erb
<h1>Boards</h1>
<div class="header">
  <hr />
    <button class="ui inverted purple button"><%= link_to 'Create New Board', new_board_path %></button>
  <hr />
</div>

  <% @boards.each do |board| %>
    <div class="ui cards">
      <div class="card">
        <div class="content">
          <div class="header">
            <%= link_to board.name, board_lists_path(board) %>
          </div>
          <div class="extra content">
            <div class="ui two buttons">
              <div class="ui basic green button"><%= link_to 'Edit', edit_board_path(board) %></div>
              <div class="ui basic red button"><%= link_to 'Delete', board, method: :delete %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    

app/views/boards/new.html.erb
<h1>Boards#new</h1>
<p>Find me in app/views/boards/new.html.erb</p>

app/views/boards/show.html.erb
<hr />
<%= link_to 'Create a new list', new_board_list_path(@board) %>
<hr />
<%= link_to 'View Lists', board_lists_path(@board) %>
<br />
<%= link_to 'Edit Board', edit_board_path(@board) %>
<br />
<%= link_to 'Delete Board', @board, method: :delete %>
  
  




  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<h1><%= @list.id ? 'Edit List' : 'Create List' %></h1>
<hr />
<%= form_for [@board, @list] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1><%= @board.name %></h1>
<hr />
<h3>Click a List To View Tasks</h3>
<hr />
<%= link_to 'Boards', boards_path %> |
<%= link_to 'Create a New List', new_board_list_path(@board) %>
<hr />

 <% @lists.each do |list| %>
  <div class="ui cards">
  <div class="card">
    <div class="content">
      <div class="header">
        <%= link_to list.name, [@board, list] %>
      </div>
      <div class="extra content">
        <div class="ui two buttons">
          <div class="ui basic green button"><%= link_to 'Edit', edit_board_list_path(@board, list) %></div>
          <div class="ui basic red button"><%= link_to 'Delete', [@board, list], method: :delete %></div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<h1><%= @board.name %> - <%= @list.name %></h1>

<button class="ui secondary button">
<%= link_to 'Back To Lists', board_lists_path(@board) %>
</button>

<button class="ui secondary button">
<%= link_to 'Add Task', new_list_task_path(@list) %>
</button>
<hr />
<% @list.tasks.each do |task| %>
  <div class="ui cards">
  <div class="card">
    <div class="content">
      <div class="header"><%= @list.name %></h1></div>
      <div class="description">
      <%= render 'tasks/task', { task: task } %> 
      <%= link_to 'Edit', edit_list_task_path(@list, task) %> 
       <%= link_to 'Delete', list_task_path(@list, task), method: :delete %>
      </div>
    </div>
    <div class="ui bottom attached button">
      <i class="add icon"></i>
      <%= link_to 'Add Task', new_list_task_path(@list) %>
    </div>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<h1><%= @task.id ? 'Edit Task' : 'Create Task' %></h1>
<%= form_for [@list, @task] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br />
  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<hr />
<p>Task: <%= task.name %></p>
<p><strong><%= task.body %></strong></p>
</hr>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>